### ISSUE TITLE
Volume of Mutual Funds are returning 0

### ISSUE THREAD

**Issue by emmagriff** [laresbernardo/lares#10]
Tried my own file of MFs with Lares' dummyPortfolio format. Loaded data in correctly but when I ran get_stocks_hist volume column was set to all zeroes. When I run dfp<-stocks_objects(df), dfp returns Lares' data, not mine.

**Comment by laresbernardo** [comment]
Hello @emmagriff 
Thanks for opening this thread with your issue. 
I've just adjusted some functions and should be running well with your `xlsx`. 
The zeroes stuff can't be fixed by me because it is a yahoo's thing when quoting your stocks... but the logic behind it yes! 
Please, run `devtools::install_github("laresbernardo/lares")`, fully close your Rstudio, and reopen it to try again. Let me know if it ran OK? If not, please reply with your code and error messages.
BTW, your Excel file is kind of weird because you invested since like 2009 and your first deposit was in 2018.. check those logs so the tool reflects your true portfolio's history and performance!

**Comment by laresbernardo** [comment]
I ran this and it worked just fine:
```
library(lares)
setwd("~/Desktop") # This is were I had the file you sent me!
df <- get_stocks(filename = "emma.xlsx")
dfp <- stocks_objects(df)
```

**Comment by emmagriff** [comment]
This worked!! Thanks so much Lares!!

**Comment by emmagriff** [comment]
Hey Lares!

Can you tell me what the gray plot represents versus the red and blue lines
in the first plot? The axes say daily var and % var. I’m assuming variance?

Let me know,

Thanks for your help!

Emma

**Comment by laresbernardo** [comment]
Yes, daily and overall variance. Red bars are negative, green bars positive and the black line is the cumulative variance since beginning of times

**Comment by emmagriff** [comment]
Yea but how can you have negative variance?

**Comment by laresbernardo** [comment]
If the previous date the value was 100 and today is 95, then the variance would be (-)5%
