### ISSUE TITLE
lares - plot_timeline size of group names

### ISSUE THREAD

**Issue by anelda** [laresbernardo/lares#15]
Hi @laresbernardo, 

I find that my group names are truncated when I don't have enough entries per group to provide the padding needed to write out the full name of the group. Is there a way to pad the blocks in which the group names appear to prevent this?

I can share my data and script with you to demonstrate the issue.

Thanks!

**Comment by anelda** [comment]
Hi @bernardolares,

I think I fixed this problem by changing the `facet_grid` line in the code to 
`  facet_grid(type ~ ., scale = 'free')`

Thanks,

Anelda

**Comment by laresbernardo** [comment]
Hi again @anelda 

I'd rather recommend you establish shorter `type` names and maybe stretch the plot a bit so those group names enter as they should. 

The reason I added ´space= "free"´ is because if you have, let's say, 3 from a group and 15 from another group, when you plot it like suggested you will be splitting the whole space equally for both (1/30 instead of 1/18 space for each bar).
