### ISSUE TITLE
Ranked Cross-Correlations

### ISSUE THREAD

**Issue by Craigdux** [laresbernardo/lares#29]
Hi, Great package, but trying to plot ranked cross-correlations. Plot looks fine, but how do I get negative correlations bars to go to left of zero? I see it in some of your examples.  Thanks!

I have attached a small part of my graph:
![Capture](https://user-images.githubusercontent.com/75813367/101835975-99254380-3b0a-11eb-8a8d-1a1106cecf63.JPG)

**Comment by laresbernardo** [comment]
Hi @Craigdux Glad to know it's working alright for your project. 
Originally, the output was designed to be as you mention: a "tornado" format plot, in which negatives grew to the left and positives to the right, arranged by absolute values from top to bottom. But, as it was too widely spread, it was harder to compare between the values and their incremental differences and that's why I plotted them all to the right. 
When using `corr_cross` you can set the `plot = FALSE` parameter to get the data instead of the plot. Then you can create a custom plot as you wish. You may use the [original function's code](https://github.com/laresbernardo/lares/blob/master/R/correlations.R#L414) as a starting point.
Good luck and feel free to share your output ;)
