### ISSUE TITLE
Keep original row names when running h2o_automl

### ISSUE THREAD

**Issue by verganimarco97** [laresbernardo/lares#41]
Hi Bernardo and congrats for lares, it is a very interesting package. When i pass a dataframe to h2o_automl it seems that the original rownames of the dataframe  get lost. In my case, for example, the names of the rows represents the IDs of the customers, so it is very important to have the possibility to link the prediction to this ID. Is there any way to keep the original rownames so that when I extract the prediction with ''$scores_test they are still there?
Thank you in advance

**Comment by laresbernardo** [comment]
Hi @verganimarco97 thanks for your feedback!
Your rownames are lost because we use dplyr underneath. I can add save those rownames for you in the backend and rename before returning results but you could also add rownames as a new column, say customer_id, and at that to the ignore parameter so it's not used as a predictor. Makes sense?

**Comment by verganimarco97** [comment]
> Hi @verganimarco97 thanks for your feedback! Your rownames are lost because we use dplyr underneath. We could save those rownames for you in the backend and include them before returning results. For now, you could add rownames as a new column, say customer_id, and add that to the `ignore` parameter so it's not used as a predictor. Makes sense?

The second option makes very sense! Which is the argument to ignore one of the variable?

**Comment by verganimarco97** [comment]
It worked, thank you!
