### ISSUE TITLE
"No valid data provided" error when running lares::h2o_automl

### ISSUE THREAD

**Issue by pangka** [laresbernardo/lares#6]
Hello,
Read your excellent blog.
Tried reproducing your h2o_automl blog example.
Ran this code: results <- lares::h2o_automl(df = Titanic, max_models = 10)
Getting this error: "Error in roc.default(results$scores$tag, results$scores$score, ci = T) : No valid data provided."
h2o starts, begins evaluating GBM models, then halts.
Retried using code from your blog--same result

**Comment by laresbernardo** [comment]
Hello @pangka 
Thanks for writing. I know exactly what the error is and I've just fixed it. Please, run lares::updateLares(), close your RStudio and open it again! 
The issue was a renaming from `results$scores` into `results$scores_test` for better labelings. Didn't caught all of them.
Let me know if that fixed your issue

**Comment by pangka** [comment]
Hello again,
Yes, that fixed it. Thank you very much!
